### ISSUE TITLE
[en] consistency: audio interface / sound card / ...and others

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#168]
Another consistency wording across the documentation.

The texts are written sometimes with one, sometimes with another of the following:
* audio interface
* soundcard
* sound card
* sound device
* sound interface
* audio device
* audio card

From what I have been able to see, there is no difference in meaning in the use of one or the other in the texts on the pages of jamulus.io .

I suggest here that we choose one so as not to disturb readers (especially beginners) who might wonder if there is a difference between "sound card" and "audio interface" in our texts. I suggest "audio interface" because it is the most neutral and encompassing of terms.

Thoughts?

**Comment by ann0see** [comment]
Sound card should refer to the internal sound card of a PC. Audio Interface to an external device in my opinion. 

We must consider that many people will not use an interface for the first run of Jamulus

**Comment by ignotus666** [comment]
> Sound card should refer to the internal sound card of a PC. Audio Interface to an external device in my opinion.

I agree. Some thoughts:

- When we recommend purchasing a separate device to improve on the integrated audio, we mean an 'audio interface'.

- This audio interface is to replace the internal integrated 'sound card'.

- We often refer to making connections without specifying either of the above, so a generic name is required. I think 'sound card' covers both of them. Although we've been using it to refer to integrated audio, if someone's bought or owns an external interface they'll know it means that. Introducing a third 'generic' name might lead to confusion ("'audio device'? But I haven't bought one yet... I'm using the internal sound card").

**Comment by gilgongo** [comment]
> Introducing a third 'generic' name might lead to confusion

Yes. Although in English we may be able to use "equipment" or "hardware" to avoid having to specify  "your computer's sound card or your audio interface if you have one". So, "connect to your equipment" or "device driver for your sound hardware" maybe?

**Comment by gegeweb** [comment]
What about "audio device(s)"? Because we can use an USB microphone, an USB amp modelizer, audio interfaces, digital mixing consoles, internal sound card… so "audio devices" cover all of this. I prefer "audio" vs "sound" because we works with the audio, not the sound.

**Comment by gilgongo** [comment]
We can assume that anyone with an external interface will know that they also have an internal one in their machine. So they would also not be confused by the term "audio device" or similar because of that. And (presumably) that means they also understand they would have multiple device drivers on their machine.

But we cannot assume anyone without an external interface will know those things. They are likely to just see their computer as the interface and therefore be confused if we refer to "audio interface" or similar. This is why I wonder if "equipment" is better if that would also mean "computer" to some people.

So I guess what words we use will depend on the context. If we audit any reference to hardware that we currently have and ask ourselves whether we are being ambiguous to that second (possibly non-technical) group?

**Comment by ann0see** [comment]
> I think 'sound card' covers both of them.

Probably yes. The problem is, how far we go. Should we also address people who don't know what a sound card (internal one) is? I think so.

We must keep in mind that there might be people who don't know how to use anything else than "Going to Google" which in fact means that they open their browser which has set Google as homepage. Some might barely know how to install an application on their own.  (At least I work with some people of this skill level).

**Comment by gilgongo** [comment]
Put it this way - if somebody doesn't know that a computer contains a sound card and they only see a USB port into which to plug, say, a mic, then "connect your mic to your sound card", "or select your desired sound card driver" is going to cause a comprehension problem.

I think the best we can do is just minimise ambiguity in context where we can. I don't think this can be done by adopting consistent language.  

So sometimes we'd need to say "audio device" or maybe "sound card" if we prefer (eg "there are a many audio devices you can use with Jamulus"), but other times we'd need do it differently (eg "your sound driver will be listed in the menu"). 

The objective is comprehension, not consistency.

**Comment by ann0see** [comment]
> The objective is comprehension, not consistency.

Yes, I Agree. Same with #146 

I think we should make this priority and put it somewhere in a contribution file.

**Comment by gegeweb** [comment]
And what about a footnote (glossary) when it's needed?

For example (something like):

Connect your microphone ou instrument to your audio device[^1]

…

[^1]: _audio device_ could be your external audio interface, your internal soundcard, your USB Microphone… it depend of hardware you're using

**Comment by ann0see** [comment]
Although this could be a solution, I don't really feel that this is the right one. In my opinion, the user should understand right away what's what. I know that's difficult ;-).

**Comment by gilgongo** [comment]
We can use footnotes if we can't work out a way of clarifying it easily I think. But in some cases we might not need to. It depends :-)

**Comment by gene96817** [comment]
I like "sound card" because it has a tangible feel. A sound card can be integrated into the mainboard.
In contrast "device" is very generic and indistinct to non-technical users.
I don't expect non-technical people will have trouble plugging a microphone or headphones to connect those things to the sound card.

**Comment by gilgongo** [comment]
@gene96817  I disagree - see my point here: https://github.com/jamulussoftware/jamuluswebsite/issues/168#issuecomment-743317373

We can agree to use a standard term if we need to refer to a specific _thing_ though (so, sound card rather than sound device for example). It's just that if we try to refer to it in the same way all the time it will cause problems.

**Comment by ann0see** [comment]
@trebmuh, I think we should start proof reading the whole documentation especially focusing on consistency discussions?
This would mean we'd solve https://github.com/jamulussoftware/jamuluswebsite/projects/3#card-51239832

**Comment by gilgongo** [comment]
Done as part of #286
