### ISSUE TITLE
[Bug] Download icon might be too difficult to reach?

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#213]
**URL**
See the windows/macOS install page and the Getting Started page.

**Describe the bug**

We already talked about this issue but at the moment I have the impression that we might have gone too far.

We want as many people as possible to get through the docs. At the moment this is done by not showing the download button until the users reach the operating system setup pages. This might lead to some people not finding the download link or thinking it’s too difficult to setup Jamulus and to more links to the SourceForge download page.

**Ideas**
We might add a download button under ”Now that you have the basics down, let’s go:“

Any thoughts on that?

But with a sentence saying that you should read on.

**Comment by gilgongo** [comment]
I think it's probably true that most people just grab the installer as soon as they can, run it and then see what happens before looking at the docs. This is/was partly why Getting Started is written as it is with advice about things like not using WiFi - because I assumed nobody would want to read more than a few lines before they started out. 

Perhaps the logical conclusion of that is to turn it around and just have a big "Download" button with a link to further info which won't get clicked, and then make it easy to get to the docs from the application once it's running?

**Comment by gilgongo** [comment]
This issue is probably now part of https://github.com/jamulussoftware/jamuluswebsite/issues/213 Close this?

**Comment by pljones** [comment]
> This issue is probably now part of #213 Close this?

Circular reference...

**Comment by gilgongo** [comment]
Close this issue #213 I mean.
