### ISSUE TITLE
Add translate as way to contribute to homepage

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#279]
Apart from that, I suggest to add this sentence in the "Contribute!" block on https://jamulus.io/:

> Contribute!
> 
> Ideas? Found a bug? Want to contribute? **_Or help translating into your language?_** Since Jamulus is free and open source software licensed under the GPL you can help us!

_Originally posted by @jerogee in https://github.com/jamulussoftware/jamulus/issues/77#issuecomment-769421362_

**Comment by gilgongo** [comment]
Yes. Also BTW @pljones raised the issue that in English, the word "contribute" means donating money, which it can do in some contexts. Although I think it's rather doubtful anyone would actually think we want monetary contributions, perhaps we might say "Help out!" rather than "Contribute!"? Although that phrase can be used to imply monetary donation too, I think it's perhaps a bit softer. 

Not sure if this is an issue in other languages.

**Comment by ignotus666** [comment]
What about "collaborate"?

**Comment by gilgongo** [comment]
Yes - and there is "participate" too. Neither of which imply  money so that's good. Although "collaboration" tends to get used as a function (so Jamulus is collaborative software - a possible ambiguity?)

**Comment by gilgongo** [comment]
I'm leaning toward "participate", although by chance the term "help out" interestingly echoes "need help?" on the home page...

Choices, choices...!

**Comment by pljones** [comment]
> Contribute!

This is what I was thinking could be "Want to get involved?"  (The exclamation mark itself makes the original an order...)

> Ideas? Found a bug? _Want to contribute?_ Or help translating into your language? Since Jamulus is free and open source software licensed under the GPL you can help us!

I think - reading it again - it actually meant "Got some code for us?" as something that could be contributed.  That, itself, should be mentioned.

**Comment by gilgongo** [comment]
OK so if the heading is "Want to get involved?" and the body says:

"_Ideas? Found a bug? Want to contribute some code or help translating into your language? Since Jamulus is free and open source software licensed under the GPL you can help us!"_

I like "want to get involved?" because of its oblique reference to [The Chicken and the Pig](https://en.wikipedia.org/wiki/The_Chicken_and_the_Pig).
