### ISSUE TITLE
New Header (Top navbar)

### ISSUE THREAD

**Issue by mulyaj** [jamulussoftware/jamulussoftware.github.io#349]
This is semi-related to #322. I think we should have a new consistent header throughout with links to important pages like download, setup, and docs.

I have this design at the moment: 
![image](https://user-images.githubusercontent.com/63881221/110197731-90978d00-7e1b-11eb-9ed5-bd773d6dc310.png)

If we were to keep these links - setup (or installation, as it is now) would either need to link to the OS-specific page, or link to a general setup page that has links to the OS-specific setup. 

For the documentation link, I'm not entirely sure where this would link - possibly jamulus.io/wiki? However, that page is fairly unorganized at the moment.

Would like to hear your thoughts.

**Comment by ann0see** [comment]
From my first impression, this looks much better then the current one. How would the homepage look like?

> For the documentation link, I'm not entirely sure where this would link - possibly jamulus.io/wiki

I think jamulus.io/wiki/Getting-Started is the page we usually link if we refer to the documentation

**Comment by gilgongo** [comment]
Yes this is much better! 

A download page is in the works of course, but what about the other links? 

What do we think about making Documentation https://jamulus.io/wiki/Software-Manual?  I ask because there is this https://github.com/jamulussoftware/jamulus/discussions/1134 which is about how Getting Started and Onboading may now overlap too much I think. The result of this discussion could be a new Setup page?

So how about making the links on the main nav "hub" pages with their own layout in the same way that Downloads has its own? The right hand nav can then be for when you're on Documentation, which in turn means we can have a bigger list of links there I think.

If we want to put this header out once the Downloads page is done, then we can make "Setup" Onboarding  and "Documentation"  Getting-Started perhaps?

**Comment by mulyaj** [comment]
> If we want to put this header out once the Downloads page is done, then we can make "Setup" Onboarding and "Documentation" Getting-Started perhaps?

Yeah that works - you mean changing the link names like this right?

![image](https://user-images.githubusercontent.com/63881221/111384465-ea9c1c00-867f-11eb-8fe2-83c173c9ad08.png)

**Comment by gilgongo** [comment]
Sorry, I meant keep the wording but have them link to those places. We don't really have an exact matches for "Documentation",  but I think it would be an expected thing in the header so linking it to Getting-Started would be sort of OK. Long term, I think we should have the current Software Manual page as the "Documentation hub" and perhaps only have the right nav on those pages (and not on Download, Setup or the home page). The reason being that we could have more links on the right if we did that (since it would be the docs area). Too many links to things on the other "top level" pages looks a bit daunting.

**Comment by ann0see** [comment]
Renamed this issue to focus on the header only

**Comment by ann0see** [comment]
Closing since it looks stale.

**Comment by ann0see** [comment]
If we want to update the website, I think a larger project must be opened.
