### ISSUE TITLE
Document delay panning

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#389]
The short description can be: 
--delaypan       Switches the server to 'delay panning' mode instead of the default 'volume panning' mode. 

A bit more detailed description (elsewhere) can be: 
When using a Jamulus server in 'delay panning' mode, the musicians listening under their head­phones can hear each other outside of their heads like in a physical meeting. The heard directions to the others can be con­trol­led by the respective PAN knobs. To achieve this result, all client Jamuli should be set to 'mono in / stereo out'.

_Originally posted by @DetlefHennings in https://github.com/jamulussoftware/jamulus/issues/1151#issuecomment-804901574_

**Comment by gilgongo** [comment]
Presumably we can put this into the "What's this?" tooltip as well as the server docs. I'd suggest something more like:

"Delay panning uses small differences in sound arrival time between the two ears. It produces a stereo effect similar to natural human hearing when compared to normal "volume" panning. Note that to achieve the effect, all clients should be set to 'mono in / stereo out' (or to 'stereo', but only if transmitting a stereo signal)."

**Comment by ann0see** [comment]
Yep

> all clients should be set to 'mono in / stereo out'

Or stereo ;-).

**Comment by DetlefHennings** [comment]
I would prefer to avoid 'psycho-acoustics' because this may not explain anything to poeple, who are not familiar with this term.  
... and please have in mind that setting a client to 'stereo' only works well with delay panning, if this client transmits a stereo signal (from stereo microphones or from another stereo source).  
We could write something like this:
"Delay panning means using small differences in sound arrival time between the two ears and is similar to natural human hearing. That's why it sounds more realistic than volume panning. Note that to achieve this, all clients should be set to  'mono in / stereo out' (or to 'stereo', but only if transmitting a stereo signal)."

**Comment by gilgongo** [comment]
Done. Not sure why this wasn't close automatically on the merge though. Hm.

**Comment by ann0see** [comment]
Maybe it wasn't linked?

**Comment by gilgongo** [comment]
It was (well, is), but I think the project automation doesn't have a condition for "if PR on linked to issue closes, move issue to done". For some reason I thought it did (and the wording on the link above says "Successfully merging a pull request may close this issue." - weird). I guess maybe that would be problematic if more than on PR was linked?

**Comment by ann0see** [comment]
> I guess maybe that would be problematic if more than on PR was linked?

Could be.
