### ISSUE TITLE
Use button for installation guides

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#488]
Is there any reason why the buttons for the installation guides have been removed in the upcoming website release and are now just "invisible" links? I think we should still make them prominent on the Setup page to make the workflow easy.

**Comment by gilgongo** [comment]
The reason is that I would think most people can probably skip that section since they'll have already installed Jamulus by the time they're on that page. So it doesn't need to heavily called out. In fact once we have a more prominent "Download" link on the new nav with a single download page explaining the basics, I was thinking of removing that section anyway.

**Comment by ann0see** [comment]
Ok. But this is only true as soon as the downloads page exists

**Comment by gilgongo** [comment]
OK sure.

**Comment by ann0see** [comment]
So I would suggest to add the buttons for now to make the guides more visible

**Comment by gilgongo** [comment]
Fixed with https://github.com/jamulussoftware/jamuluswebsite/pull/524
