### ISSUE TITLE
Exclude translator_files from being pushed to gh-pages

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#519]
Currently the translator_files folder and both scripts are pushed to the gh-pages branch. Since they are not needed there, we could probably somehow exclude them.

**Comment by ignotus666** [comment]
Put the scripts in a folder and prepend it (and translator-files) with an underscore? I tested that and it seems to work.

**Comment by ann0see** [comment]
Argh yes this should work. I should have known that.

**Comment by ignotus666** [comment]
Paths in the scripts have to be changed accordingly, too. [This](https://github.com/ignotus666/jamuluswebsite/tree/GH_actions_test2) branch has "excluded" folders for the scripts and po4a .deb package ("po4a-tools") and "translator-files". The paths in these scripts have been modified. Putting the scripts in a folder caused them to not work via GH actions (they did locally) due to how paths are established in actions, so the scripts have also been modified to work in that scenario.

Just documenting this info here for future reference. I don't trust myself not to forget about it.
