### ISSUE TITLE
Add Dutch [nl]

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#646]
# Language you want to translate to
Dutch

# Description
I would like to add Dutch translation to the Jamulus web-site

**Comment by ignotus666** [comment]
Hi @henkdegroot, thanks for volunteering! As per the above message, the files for Dutch are now ready for translation. If you have any questions about the process, please don't hesitate to ask.

**Comment by henkdegroot** [comment]
Many thanks, I will start working the translation.

Does this mean that the Dutch text will only appear with the next Jamulus version or can it be that the web-site be updated before  that?

**Comment by ignotus666** [comment]
It would be published with the next release. The way it's set up, translations happen on the 'next-release' branch, which gradually moves ahead of the 'release' branch as changes are made and the app release approaches. Edits/corrections can be made to existing languages on 'release', but unfortunately adding a new language to it is not currently "supported" - I'm not 100% sure but I think it could potentially lead to conflicts between branches.

**Comment by henkdegroot** [comment]
No problem, thanks for clarifying. At least that sounds like I have a bit of time to complete the translation.

**Comment by ignotus666** [comment]
Also: from now until there is a new release, things will inevitably change, meaning that some parts of translations done now will become obsolete - in order to avoid this, it might be best to wait until the freeze period starts a few weeks before the release. There's nothing stopping you from starting now if you prefer to give yourself more time, but be aware that there will be changes. Typically it isn't that much - a few things are removed, others added and others moved around. Tip: make sure you use a translation memory (instructions in the README).

**Comment by henkdegroot** [comment]
Sure things will change, but many will remain the same as well. So won't be wasting time and it is a good learning exercise.
I am familiarizing myself with OmegaT, which seems to work very nice. Just had a bit a pain setting up all prerequisites on the machine I use for this. Also finding some minor issues while I am working on this and am checking already if they have been addressed or not (before potentially creating a new issue to get it resolved).
