### ISSUE TITLE
Text alignment below images not matching

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#672]
**URL**
https://jamulus.io/wiki/Getting-Started
https://jamulus.io/wiki/Software-Manual

**Describe the bug**
All images in the Getting Started page, include a figure caption. 
The first image in the Software-Manual page contains a figure caption.

These captions are not aligned with the image. This can be best seen at the images which are a narrow.
Here an example:

![website-settings](https://user-images.githubusercontent.com/13550012/147849296-2498eefe-225a-4ed1-886e-37f080330f73.png)

It would be nicer to have the text to align with the image.

**Comment by gilgongo** [comment]
I can't reproduce this I'm afraid (on Chrome or Edge - not tried FF). Is it something to do with the view port maybe? I've tried it on various sizes.

**Comment by hoffie** [comment]
I can reproduce on both Firefox and Chrome, but only on my larger screen (1920x1080) and not on the smaller one (1280x1024).

The issue is that both the image and the caption are wrapped in a `<figure>` which takes the whole body width. The caption is centered within this range, while the image is left-aligned.. As long as the image fills the whole width, it doesn't matter.

I see the following solutions:
1. Left align the text to match the image alignment (`figcaption { text-align: left; }`). This changes existing rendering for everyone.
1. Center the image (`figure { text-align: center} figure img { display: inline-block; }` works, but might not be the most elegant way?)

I can do a PR (or anyone else an), but I don't want to decide. ;)

| **Status quo** |
| --- |
|![Screenshot 2022-01-23 at 11-50-08 Setup – Jamulus Wiki](https://user-images.githubusercontent.com/762915/150675130-e60dba19-b20a-4a03-bf19-e42aae1e7ee5.png)|

|**1. Text left aligned**|
| -- |
|![Screenshot 2022-01-23 at 11-51-41 Setup – Jamulus Wiki](https://user-images.githubusercontent.com/762915/150675146-a87921fc-0538-411f-a57d-0b8cf21a51fa.png)|

|**2. Image cenetered**|
| -- |
|![Screenshot 2022-01-23 at 11-51-14 Setup – Jamulus Wiki](https://user-images.githubusercontent.com/762915/150675144-7d78476f-8f88-4100-8214-9b81be2d97e5.png)|

**Comment by henkdegroot** [comment]
> I can't reproduce this I'm afraid

@hoffie  already indicates it is "easier" to spot this on 1920x1080 (my default resolution). Another good option is to use the browser and zoom out to say 50%.

**Comment by gilgongo** [comment]
Oh I see. I think centering the image is probably what we want to do or the caption may get confused with the body text.
