### ISSUE TITLE
[Bug] Wiki overview page shows link to pt data files

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#678]
**URL**
https://jamulus.io/es/wiki/
https://jamulus.io/de/wiki/

etc. all have two bullet points linking to /es/wiki/pt/navigation.yml or similar. I haven't found the cause yet.

**Describe the bug**
Misleading "empty" bullet points on the overview page lead to broken links. Probably something is wrong in the compilation step.

**Comment by ignotus666** [comment]
It's happening because of the `navigation.yml` and `general.yml` files symlinked to the language folders in `/wiki`. If I revert those (i.e. replace the symlinks with the original files, moving them back from `/wiki/[LANG]/`, the problem goes away. The symlinked EN files can stay; it's the language ones that cause the problem, so maybe there's a way around this, possibly by getting the po4a script to create these files directly in `_data/`.

**Comment by ignotus666** [comment]
Ok, found out how to do it. Still need to clean things up a bit and do more testing but there's a solution.

This fix could also be extended to the other files that are symlinked - it complicates the script (slightly, not much), but cleans up all those symlinks scattered around. Those files would only get created when the site is deployed, like the rest of the translated docs. On the other hand, it would simplify the `po4a-add-language.sh` script significantly.
