### ISSUE TITLE
Update "Installation-for-Linux" to support libqt5multimedia5 dependency

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#781]
The "[Installation for Linux](https://jamulus.io/wiki/Installation-for-Linux)" page for the Linux Client needs updating because of the additional dependency added under jamulussoftware/jamulus#2721, which fixed jamulussoftware/jamulus#2720.

For **Ubuntu only**, prior to the "Download Jamulus" step, we need to add:

> You will need to enable the "universe" Ubuntu repository before installing.  Please see one of the following two posts:
> * [GUI-based approach](https://askubuntu.com/a/148645)
> * [CLI-based approach](https://askubuntu.com/a/227788)

(*Note:* Debian does not have "universe", only "main", "contrib" and "non-free" and libqt5multimedia5 is in "main", so there should not be a problem.)

**Comment by ann0see** [comment]
This needs translation, so it should be done quickly after the other PR is merged

**Comment by ann0see** [comment]
The new text is a bit different on the site on next-release. I think we could add the following shorter paragraph as step 2:

2. Ubuntu only: Before installing, enable the Ubuntu "universe" repository (you can use the [GUI-based approach](https://askubuntu.com/a/148645)
 or [CLI-based approach](https://askubuntu.com/a/227788)). **Note:** Debian does *not* need this step

We could also remove the "Note" since it's redundant

**Comment by gilgongo** [comment]
Fixed with https://github.com/jamulussoftware/jamuluswebsite/pull/783

**Comment by ann0see** [comment]
@ignotus666  @jujudusud Probably you need to update the installation for linux page since we added a dependency
