### ISSUE TITLE
Some Norwegian slipped into the main jamulus.io English website

### ISSUE THREAD

**Issue by KonFey** [jamulussoftware/jamulussoftware.github.io#883]
**URL**
https://jamulus.io/

**Describe the bug**
Some Norwegian translations slipped into the main jamulus.io English website

![grafik](https://user-images.githubusercontent.com/31243074/209475072-4f486947-8918-44aa-ad17-b8a2c4141fdc.png)

**Comment by ann0see** [comment]
Thanks for the information. This must be fixed of course.

**Comment by ann0see** [comment]
I fixed it, but I think we had this issue some time before too. This happens if translations get fuzzy resulting in multiple "en" translated files. I think @ignotus666 and me need to find a solution. Best would be to not create the .md file at all if the language is not changed. Jekyll should then take care of it automatically.

**Comment by ignotus666** [comment]
Yeah, this happens if "lang: en" doesn't get changed in the 1-Index.md file for another language. But I think that if this file doesn't get created at all if not translated, none of the other files for that language are shown either. That's why it's in a small group of files that are excluded from the threshold requirement.

**Comment by ann0see** [comment]
Are you sure about that?

This would be Po4a related not jekyll related then. Jekyll handles the last part of the translation and also implements a fallback.

**Comment by ignotus666** [comment]
I'll do some tests tomorrow. I'm assuming it's why I included it in the "no threshold" group, but TBH I can't exactly remember.

(Note to self: give more info in comments in scripts.)

**Comment by ann0see** [comment]
I think we need to investigate the po files on next-release as they seem to contain invalid content: https://github.com/jamulussoftware/jamuluswebsite/actions/runs/3783627873/jobs/6432322439

**Comment by ann0see** [comment]
I think the po files are OK now. Fixing conflicts was a mess.

**Comment by ignotus666** [comment]
Ok, I finally managed to sort out Jekyll on my PC and did some tests. If the Index file is missing for any language, the website won't even build, so that's why it's in the "no threshold" group. It has to be created, even if not translated. The only thing to keep in mind is that at least the `lang:` field has to be changed to the right language.

**Comment by ann0see** [comment]
Closing as the other issue should handle the next steps for preventing this happening again. 
#918
